
images:
- name: beast-core
  newName: registry-approved.il2.gamewarden.io/agencies/project-blue/beast-core-app
  newTag: 3.10.0
- name: data-loader
  newName: registry.il4.dso.mil/platform-one/devops/pipeline-templates/beast-code-init/ironbank-bitnami-git-lfs
  newTag: 2.31.1

patches:
- patch: |-
    apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
    kind: Kustomization
    metadata:
      name: beast-core
    spec:
      path: ./il2/overlays/prod
  target:
    kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
