resources:
- ../base/
- ../../../environments/il4/staging

images:
- name: beast-core
  newName: registry-approved.il2.gamewarden.io/agencies/project-blue/beast-core-app:3.10.0
  newTag: 3.10.0
- name: data-loader
  newName: registry.il2.dso.mil/platform-one/products/beast-code/beast-code-manifests/aws
  newTag: "1.0"
  
patches:
- patch: |-
    apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
    kind: Kustomization
    metadata:
      name: beast-core
    spec:
      path: ./overlays/il4/staging
  target:
    kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
