apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: beast-core
  namespace: beast-core
spec:
  path: ./overlays/il2/dev
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: beast-core-manifest
  prune: true
  decryption:
    provider: sops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: secrets
  namespace: beast-core
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: beast-core-manifest
  path: ./overlays/il2/dev/secrets
  prune: true
  decryption:
    provider: sops
